"use client";

import { useCallback, useRef, useState } from "react";

import type {
  Credential,
  ProvenanceMethod,
  StorageProof,
  Verification,
} from "@/lib/veritable/types";

type Issued = { credential: Credential; proof: StorageProof };

type Mode = "idle" | "uploading" | "verifying";

const PROVENANCE_OPTIONS: { value: ProvenanceMethod; label: string }[] = [
  { value: "ai-generated", label: "AI-generated" },
  { value: "human-authored", label: "Human-authored" },
  { value: "captured", label: "Captured (photo/recording)" },
];

export function VeritableApp() {
  const [provenance, setProvenance] = useState<ProvenanceMethod>("ai-generated");
  const [claim, setClaim] = useState("");
  const [model, setModel] = useState("");
  const [prompt, setPrompt] = useState("");
  const [issuer, setIssuer] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [text, setText] = useState("");
  const [mode, setMode] = useState<Mode>("idle");
  const [error, setError] = useState<string | null>(null);
  const [issued, setIssued] = useState<Issued | null>(null);
  const [verification, setVerification] = useState<Verification | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const reset = useCallback(() => {
    setIssued(null);
    setVerification(null);
    setError(null);
  }, []);

  const onPickFile = (f: File | null) => {
    setFile(f);
    setText("");
    reset();
  };

  const onPickText = (t: string) => {
    setText(t);
    setFile(null);
    reset();
  };

  const canSubmit =
    mode === "idle" && claim.trim().length > 0 && (file !== null || text.trim().length > 0);

  const handleIssue = useCallback(async () => {
    if (!canSubmit) return;
    setMode("uploading");
    setError(null);
    setIssued(null);
    setVerification(null);

    try {
      const form = new FormData();
      form.set("provenance", provenance);
      form.set("claim", claim.trim());
      if (issuer.trim()) form.set("issuer", issuer.trim());
      if (model.trim()) form.set("model", model.trim());
      if (prompt.trim()) form.set("prompt", prompt.trim());

      if (file) {
        form.set("artifact", file, file.name);
      } else {
        form.set("text", text);
      }

      const res = await fetch("/api/credentials", { method: "POST", body: form });
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data?.error ?? "Failed to issue credential.");
      }
      setIssued(data as Issued);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Something went wrong.");
    } finally {
      setMode("idle");
    }
  }, [canSubmit, claim, file, issuer, model, prompt, provenance, text]);

  const handleVerify = useCallback(async () => {
    if (!issued) return;
    setMode("verifying");
    setError(null);
    setVerification(null);
    try {
      const res = await fetch(`/api/credentials/${issued.credential.id}/verify`, {
        method: "POST",
      });
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data?.error ?? "Verification failed.");
      }
      setVerification((data as { verification: Verification }).verification);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Something went wrong.");
    } finally {
      setMode("idle");
    }
  }, [issued]);

  return (
    <div className="mx-auto flex min-h-screen w-full max-w-3xl flex-col gap-8 px-6 py-12">
      <Header />

      {error && (
        <div className="glass rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-200">
          {error}
        </div>
      )}

      <section className="glass rounded-2xl p-6">
        <h2 className="mb-1 text-lg font-semibold">Issue a credential</h2>
        <p className="mb-6 text-sm text-neutral-400">
          Attach an artifact and provenance. Veritable commits it to 0G Storage and
          returns a tamper-evident credential anchored on the 0G chain.
        </p>

        <div className="grid gap-5">
          <ArtifactInput
            file={file}
            text={text}
            onPickFile={onPickFile}
            onPickText={onPickText}
            fileInputRef={fileInputRef}
          />

          <Field label="What does this credential claim?">
            <input
              type="text"
              value={claim}
              onChange={(e) => {
                setClaim(e.target.value);
                reset();
              }}
              placeholder="e.g. Generated by Acme Studio's image model"
              className="w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm outline-none focus:border-violet-400/60"
            />
          </Field>

          <div className="grid gap-5 sm:grid-cols-2">
            <Field label="Provenance">
              <select
                value={provenance}
                onChange={(e) => {
                  setProvenance(e.target.value as ProvenanceMethod);
                  reset();
                }}
                className="w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm outline-none focus:border-violet-400/60"
              >
                {PROVENANCE_OPTIONS.map((o) => (
                  <option key={o.value} value={o.value} className="bg-neutral-900">
                    {o.label}
                  </option>
                ))}
              </select>
            </Field>
            <Field label="Issuer (optional)">
              <input
                type="text"
                value={issuer}
                onChange={(e) => {
                  setIssuer(e.target.value);
                  reset();
                }}
                placeholder="anonymous"
                className="w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm outline-none focus:border-violet-400/60"
              />
            </Field>
          </div>

          {provenance === "ai-generated" && (
            <div className="grid gap-5 sm:grid-cols-2">
              <Field label="Model (optional)">
                <input
                  type="text"
                  value={model}
                  onChange={(e) => {
                    setModel(e.target.value);
                    reset();
                  }}
                  placeholder="e.g. stable-diffusion-xl"
                  className="w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm outline-none focus:border-violet-400/60"
                />
              </Field>
              <Field label="Prompt (optional)">
                <input
                  type="text"
                  value={prompt}
                  onChange={(e) => {
                    setPrompt(e.target.value);
                    reset();
                  }}
                  placeholder="the prompt that produced it"
                  className="w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm outline-none focus:border-violet-400/60"
                />
              </Field>
            </div>
          )}

          <button
            type="button"
            onClick={handleIssue}
            disabled={!canSubmit}
            className="mt-2 w-full rounded-lg bg-violet-500 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-violet-400 disabled:cursor-not-allowed disabled:bg-white/10 disabled:text-neutral-500"
          >
            {mode === "uploading" ? "Committing to 0G…" : "Issue credential on 0G"}
          </button>
        </div>
      </section>

      {issued && (
        <ProofPanel
          issued={issued}
          mode={mode}
          verification={verification}
          onVerify={handleVerify}
        />
      )}
    </div>
  );
}

function Header() {
  return (
    <header className="flex flex-col gap-3">
      <div className="flex items-center gap-3">
        <span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1 text-xs font-medium text-neutral-300">
          <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
          Built on 0G
        </span>
      </div>
      <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Veritable</h1>
      <p className="text-neutral-400">Prove what&rsquo;s real in the AI age.</p>
    </header>
  );
}

function Field({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <label className="flex flex-col gap-1.5">
      <span className="text-xs font-medium uppercase tracking-wide text-neutral-500">
        {label}
      </span>
      {children}
    </label>
  );
}

function ArtifactInput({
  file,
  text,
  onPickFile,
  onPickText,
  fileInputRef,
}: {
  file: File | null;
  text: string;
  onPickFile: (f: File | null) => void;
  onPickText: (t: string) => void;
  fileInputRef: React.RefObject<HTMLInputElement | null>;
}) {
  return (
    <div className="flex flex-col gap-3">
      <div className="flex gap-2">
        <button
          type="button"
          onClick={() => fileInputRef.current?.click()}
          className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm hover:border-violet-400/60"
        >
          {file ? file.name : "Choose file…"}
        </button>
        <input
          ref={fileInputRef}
          type="file"
          className="hidden"
          onChange={(e) => onPickFile(e.target.files?.[0] ?? null)}
        />
        <span className="self-center text-xs text-neutral-500">or paste text</span>
      </div>
      <textarea
        value={text}
        onChange={(e) => onPickText(e.target.value)}
        placeholder="Paste the artifact text here (or choose a file above)…"
        rows={4}
        className="w-full resize-y rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm outline-none focus:border-violet-400/60"
      />
    </div>
  );
}

function ProofPanel({
  issued,
  mode,
  verification,
  onVerify,
}: {
  issued: Issued;
  mode: Mode;
  verification: Verification | null;
  onVerify: () => void;
}) {
  const { credential, proof } = issued;
  const isLocal = proof.mode === "local";

  return (
    <section className="glass flex flex-col gap-5 rounded-2xl p-6">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold">Credential issued</h2>
        <span
          className={`rounded-full px-2.5 py-1 text-xs font-medium ${
            isLocal
              ? "bg-amber-500/15 text-amber-300"
              : "bg-emerald-500/15 text-emerald-300"
          }`}
        >
          {isLocal ? "Local mode" : "Anchored on 0G"}
        </span>
      </div>

      <div className="grid gap-4 text-sm">
        <Row label="Artifact SHA-256" value={credential.artifact.sha256} mono />
        <Row label="Kind" value={credential.artifact.kind} />
        <Row label="Claim" value={credential.claim} />
        <Row label="Provenance" value={credential.provenance} />
        {credential.model && <Row label="Model" value={credential.model} />}
        <Row label="Issued" value={credential.issuedAt} />
      </div>

      <div className="rounded-xl border border-white/10 bg-black/30 p-4">
        <h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-neutral-500">
          Verify on 0G
        </h3>
        <div className="grid gap-2 text-xs">
          <Row label="Root hash" value={proof.rootHash} mono small />
          {proof.transactionHash && (
            <Row label="Transaction" value={proof.transactionHash} mono small />
          )}
          {proof.transactionUrl && (
            <a
              href={proof.transactionUrl}
              target="_blank"
              rel="noreferrer"
              className="text-violet-300 hover:underline"
            >
              View on 0G explorer ↗
            </a>
          )}
          {proof.uploaderAddress && (
            <Row label="Uploader" value={proof.uploaderAddress} mono small />
          )}
          {proof.chainId && <Row label="Chain ID" value={proof.chainId} small />}
        </div>
      </div>

      <button
        type="button"
        onClick={onVerify}
        disabled={mode !== "idle"}
        className="w-full rounded-lg border border-violet-400/40 bg-violet-500/10 px-4 py-2.5 text-sm font-semibold text-violet-200 transition hover:bg-violet-500/20 disabled:opacity-50"
      >
        {mode === "verifying" ? "Verifying against 0G…" : "Verify credential on 0G"}
      </button>

      {verification && <VerificationResult v={verification} />}
    </section>
  );
}

function VerificationResult({ v }: { v: Verification }) {
  const allPass =
    v.merkleProofVerified &&
    v.decryptionSucceeded &&
    v.artifactHashMatched &&
    (v.issuerMatched ?? true);
  return (
    <div className="rounded-xl border border-white/10 bg-black/20 p-4">
      <div className="mb-3 flex items-center gap-2">
        <span
          className={`h-2 w-2 rounded-full ${
            allPass ? "bg-emerald-400" : "bg-red-400"
          }`}
        />
        <h3 className="text-sm font-semibold">
          {allPass ? "Verified" : "Verification failed"}
        </h3>
      </div>
      <div className="grid gap-1.5 text-xs">
        <Check label="Transaction finalized" ok={v.transactionFinalized} />
        <Check label="Merkle proof download" ok={v.merkleProofVerified} />
        <Check label="Decryption succeeded" ok={v.decryptionSucceeded} />
        <Check label="Artifact hash matched" ok={v.artifactHashMatched} />
        <Check
          label="Issuer matched"
          ok={v.issuerMatched === null ? true : v.issuerMatched}
        />
        {v.blockNumber && (
          <Row label="Block" value={String(v.blockNumber)} small />
        )}
      </div>
    </div>
  );
}

function Row({
  label,
  value,
  mono,
  small,
}: {
  label: string;
  value: string;
  mono?: boolean;
  small?: boolean;
}) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-xs uppercase tracking-wide text-neutral-500">
        {label}
      </span>
      <span
        className={`${mono ? "font-mono" : ""} ${small ? "text-xs" : ""} break-all text-neutral-200`}
      >
        {value}
      </span>
    </div>
  );
}

function Check({ label, ok }: { label: string; ok: boolean }) {
  return (
    <div className="flex items-center gap-2">
      <span
        className={`inline-flex h-4 w-4 items-center justify-center rounded-full text-[10px] ${
          ok ? "bg-emerald-500/20 text-emerald-300" : "bg-red-500/20 text-red-300"
        }`}
      >
        {ok ? "✓" : "✗"}
      </span>
      <span className="text-neutral-300">{label}</span>
    </div>
  );
}
